### ISSUE TITLE
how to define a png filename prefix?

### ISSUE THREAD

**Issue by socay1** [telesoho/vscode-markdown-paste-image#68] opened 2022-01-20 02:14 UTC
as default,  filename only is date format `2022-01-20-10-11-59.png`, how to get a customized format, ie. `prefix_2022-01-20-11.png`?

**Comment by knyzorg** [comment] 2022-01-20 20:04
Duplicate of #11

**Comment by telesoho** [comment] 2022-01-30 13:30
#69

**Closed by telesoho** 2022-01-30 13:30 UTC
